version: 3

dotenv:
  - "configs/env/default.env"
  - "configs/env/{{.ENV}}.env"

tasks:
  go:run:
    deps:
      - go:mod:tidy
    cmds:
      - go run ./cmd/hal
    sources:
      - "**/*.go"
      - go.mod

  go:mod:tidy:
    - go mod tidy

  docker:build:
    - docker compose -f build/docker-compose.yml build

  docker:run:
    deps:
      - docker:build
    cmds:
      - docker compose -f build/docker-compose.yml run --service-ports hal
    sources:
      - "**/*.go"
      - go.mod
      - build/*
