version: 3

dotenv:
  - "configs/env/default.env"
  - "configs/env/{{.ENV}}.env"

tasks:
  go:run:
    deps:
      - go:mod:tidy
    cmds:
      - go run ./cmd/hal
    sources:
      - "**/*.go"
      - go.mod

  go:mod:tidy:
    - go mod tidy

  docker:build:
    - docker build -t hal -f build/Dockerfile .

  docker:run:
    deps:
      - docker:build
    cmds:
      - docker run --rm -p 7095:7095 hal
    sources:
      - "**/*.go"
      - go.mod
      - build/*
