version: 3

dotenv:
  - "configs/env/default.env"
  - "configs/env/{{.ENV}}.env"

tasks:
  go:run:
    desc: Run without a container
    deps:
      - go:mod:tidy
    cmds:
      - go run ./cmd/hal
    sources:
      - "**/*.go"
      - go.mod

  go:mod:tidy:
    desc: Install deps
    cmds:
      - go mod tidy

  docker:build:
    desc: Build container image
    cmds:
      - docker compose -f build/docker-compose.yml build

  docker:run:
    desc: Run in a container
    deps:
      - docker:build
    cmds:
      - docker compose -f build/docker-compose.yml run --service-ports hal
    sources:
      - "**/*.go"
      - go.mod
      - build/*

  docker:up:
    desc: docker-compose up
    cmds:
      - docker compose -f build/docker-compose.yml up -d --build --remove-orphans
    sources:
      - "**/*.go"
      - go.mod
      - build/*

  docker:down:
    desc: docker compose down
    cmds:
      - docker compose -f build/docker-compose.yml down --remove-orphans

  dc:
    desc: docker compose {{.CLI_ARGS}}
    cmds:
      - docker compose -f build/docker-compose.yml {{.CLI_ARGS}}
