version: 3

dotenv: ['.env', '{{.ENV}}/.env.']

tasks:
  go:run:
    deps:
      - go:mod:tidy
    cmds:
      - go run *.go
    sources:
      - "*.go"
      - "go.mod"

  go:mod:tidy:
    - go mod tidy
